- name: List homepage URLs
  hosts: tests

  tasks:
  - name: List hompeage URLs
    shell: wp --path=/app/www plugin install jetpack
    register: shell_result
    
  - debug: var: shell_result.stdout_lines
